name: Build Vue
on:
  release:
    types: [published]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'YouHaveTrouble'
          reponame: 'cardmaker'
          token: ${{ secrets.GITHUB_TOKEN }}